version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get -y update
            apt-get -y install git
            apt-get -y install gcc meson pkg-config
            apt-get -y install libncurses-dev
      - checkout
      - run:
          name: Configure meson
          command: meson -Db_coverage=true build
      - run:
          name: Build tasker
          command: |
            cd build
            ninja
      - run:
          name: Test tasker
          command: |
            cd build
            ninja test
