name: "build"

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install git
          sudo apt-get -y install gcc meson pkg-config
          sudo apt-get -y install libboost-program-options-dev libboost-system-dev
          sudo apt-get -y install libncurses-dev

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Meson
        run: meson -Dbuild_bin=true -Dbuild_tests=false build

      - name: Build Project
        run: |
          cd build
          ninja
