name: "build"

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: apt-get Cache
        id: cache-apt
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/cache-apt
          key: ${{ runner.os }}-apt

      - name: apt-get Restore Cache
        if: steps.cache-apt.outputs.cache-hit == 'true'
        env:
          SOURCE: ${{ runner.temp }}/cache-apt
        run: |
          sudo cp --force -v ${SOURCE}/*.deb /var/cache/apt/archives/

      - name: Install Dependencies
        env:
          SOURCE: ${{ runner.temp }}/cache-apt
        run: |
          sudo apt-get -y update
          sudo apt-get -y install git
          sudo apt-get -y install gcc meson pkg-config
          sudo apt-get -y install libboost-program-options-dev libboost-system-dev
          sudo apt-get -y install libncurses-dev
          mkdir -p ${SOURCE}
          cp --force -v /var/cache/apt/archives/*.deb ${SOURCE}/

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Configure Meson
        run: meson -Dversion="$(git describe)" -Dbuild_tests=false build

      - name: Build Project
        run: ninja -C build -j2

      - name: Print Version
        run: ./build/src/tasker --version

      - name: Collect Badge Information
        run: |
          REF=${{ github.ref }}

          IFS='/' read -ra PATHS <<< "$REF"
          BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
          echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV

      - name: Create Build Status Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST }}
          gistID: 98692fb94e55e0667afb58f20b67f3f2
          filename: tasker__${{ env.BRANCH }}_build.json
          label: build
          message: "passing"
          labelColor: '#2b3136'
          color: '#6524b5'
