name: "test"

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install git
          sudo apt-get -y install gcc meson pkg-config gcovr lcov
          sudo apt-get -y install libboost-program-options-dev libboost-system-dev
          sudo apt-get -y install libncurses-dev

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Meson
        run: meson -Db_coverage=true -Dbuild_bin=false -Dbuild_tests=true build

      - name: Build Project
        run: |
          cd build
          ninja

      - name: Test Project
        run: |
          cd build
          ninja test

      - name: Generate Code Coverage Reports
        run: |
          cd build
          ninja coverage-text coverage-xml coverage-html
          cat meson-logs/coverage.txt

      - uses: actions/upload-artifact@v3
        with:
          name: meson-logs
          path: build/meson-logs

      - name: Collect Badge Information
        run: |
          REF=${{ github.ref }}

          IFS='/' read -ra PATHS <<< "$REF"
          BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
          echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV

          COVERAGE="$(cat build/meson-logs/coverage.txt | grep -oEi '^TOTAL.*[0-9]+.*[0-9]+.*([0-9]+%)$' | sed -r 's/^TOTAL\s+[0-9]+\s+[0-9]+\s+?([0-9]+%)$/\1/')"
          echo "COVERAGE=$(echo $COVERAGE)" >> $GITHUB_ENV

          echo "Branch name: '${BRANCH_NAME}'"
          echo "Coverage: '${COVERAGE}'"

      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST }}
          gistID: 98692fb94e55e0667afb58f20b67f3f2
          filename: tasker__${{ env.BRANCH }}_coverage.json
          label: coverage
          message: ${{ env.COVERAGE }}
          labelColor: '#2b3136'
          color: '#6524b5'

      - name: Create Test Status Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST }}
          gistID: 98692fb94e55e0667afb58f20b67f3f2
          filename: tasker__${{ env.BRANCH }}_test.json
          label: tests
          message: "passing"
          labelColor: '#2b3136'
          color: '#6524b5'
