name: "test"

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install git
          sudo apt-get -y install gcc meson pkg-config gcovr
          sudo apt-get -y install libncurses-dev

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Meson
        run: meson -Db_coverage=true build

      - name: Build Project
        run: |
          cd build
          ninja

      - name: Test Project
        run: |
          cd build
          ninja test

      - name: Generate Code Coverage XML
        run: |
          cd build
          ninja coverage-text
          ninja coverage-xml

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/meson-logs/coverage.xml
          badge: true
          format: markdown
          hide_branch_rate: true
          output: both

      - name: Collect Coverage for Badge
        run: |
          REF=${{ github.ref }}

          IFS='/' read -ra PATHS <<< "$REF"
          BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
          echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV

          COVERAGE="$(cat build/meson-logs/coverage.txt | grep -oEi '^TOTAL.*[0-9]+.*[0-9]+.*([0-9]+%)$' | sed -r 's/^TOTAL\s+[0-9]+\s+[0-9]+\s+?([0-9]+%)$/\1/')"
          echo "COVERAGE=$(echo $COVERAGE)" >> $GITHUB_ENV

          echo "Branch name: '${BRANCH_NAME}'"
          echo "Coverage: '${COVERAGE}'"

      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST }}
          gistID: 98692fb94e55e0667afb58f20b67f3f2
          filename: tasker__${{ env.BRANCH }}.json
          label: Test Coverage
          message: ${{ env.COVERAGE }}
          color: '#32a852'
          namedLogo: jest
